---
title: "Exercise 1"
author: "Kasper Ng Bergan"
date: "`r Sys.Date()`"
output: html_document
---

# 1a
```{r}
lao <- read.csv("data/Lao cattle.csv", header = TRUE)
str(lao)
```

# 1b
```{r}
plot(Weight ~ Girth, data = lao)
plot(log(Weight) ~ log(Girth), data = lao)
```
My conclusion about linearity is that the data looks like it has a exponential pattern, the log transformation straightens the data out.

# 1c
```{r}
lao.lm <- lm(log(Weight) ~ log(Girth), data = lao)
summary(lao.lm)
anova(lao.lm, test = "F")
```
log(Girth) close to all variation of log(Weight). I think it would be a useful method

# 1d
```{r}
library(ggplot2)
ggplot(data = lao, aes(x = log(Girth), y = log(Weight))) + geom_point() 
+ geom_smooth(method = "lm", se = FALSE, color = "red") + theme_classic()

plot(log(Weight) ~ log(Girth), data = lao)
abline(lao.lm, col = "red")
```

# 1e
```{r}
Girth <- 160
b0 <- coef(lao.lm)[1]
b1 <- coef(lao.lm)[2]
log_weight <- b1*log(Girth) + b0
exp(log_weight)

log_predict <- predict(lao.lm, data.frame(Girth = 160))
exp(log_predict)
```

# 1f
```{r}
library(ggplot2)

summary(lao$Girth)
Girth_values <- seq(50, 200, 5)
lao.pred <- predict(lao.lm, data.frame(Girth + Girth_values), interval = "prediction")

lao.pred
is.matrix(lao.pred)
is.data.frame(lao.pred)

lao.girth.pred <- data.frame(Girth = seq(50, 200, 5), exp(lao.pred))

ggplot(lao.girth.pred, aes(x = Girth, y = fit)) +
geom_line() +
geom_ribbon(aes(ymin = lwr, ymax = upr), alpha = 0.2) +
geom_point(data = lao, aes(x = Girth, y = Weight)) +
ylab("Weight (kg)") + xlab("Girth (cm)") +
theme_classic()
```


# 2a
```{r}
dippers <- read.csv("data/Breeding density of dippers.csv")
```

# 2b
```{r}
LogBrD1 <- log(dippers$Br_Dens+1)
all.equal(LogBrD1, log(dippers$Br_Dens + 1))
```

# 2c 
```{r}
summary(dippers)
```

# 2d
```{r}
Altitude <- dippers$Altitude
hist(Altitude,
     main = "Histogram",
     xlab = "Altitude")
boxplot(Altitude,
        main = "Boxplot")
```

# 2e 
```{r}
library(ggplot2)

ggplot(dippers, aes(x = LogStone, y = LogBrD)) +
geom_point() +
theme_classic()

plot(dippers$LogBrD ~ dippers$LogStone, data = dippers)

pairs(dippers[,c(1:3, 9:13)], cex = 0.5)
```

# 2f 
```{r}
dippers.lm <- lm(dippers$LogBrD ~ dippers$Gradient, data = dippers)
plot(dippers.lm)
summary(dippers.lm)
anova(dippers.lm)
```

# 2g
```{r}
dippers.lm2 <- lm(dippers$LogBrD ~ dippers$Altitude + dippers$Hardness + dippers$Gradient + dippers$LogCadd + dippers$LogStone + dippers$LogMay + dippers$LogOther, data = dippers)
summary(dippers.lm2)
anova(dippers.lm2)
```

# 2h
```{r}
drop1(dippers.lm2, test = "F")
```

# 2i
```{r}
dippers.lm3 <- lm(dippers$LogBrD ~ 1, data = dippers)
anova(dippers.lm2, dippers.lm3)
```

# 2j
```{r}
dippers.lm4 <- lm(dippers$LogBrD ~ dippers$Altitude + dippers$Hardness + dippers$Gradient, data = dippers)
anova(dippers.lm4, dippers.lm2)
```

# 2k
```{r}
library(MASS)
dippers.lm5 <- stepAIC(dippers.lm2)
```


# 3a
```{r}
library(MuMIn)
dippers.lm6 <- lm(dippers$LogBrD ~ dippers$Altitude + dippers$Hardness + dippers$Gradient + dippers$LogCadd + dippers$LogStone + dippers$LogMay + dippers$LogOther, data = dippers, na.action = na.fail)

mod.sel <- dredge(dippers.lm6, rank = "AICc")
mod.sel
```

# 3b
```{r}
mod.sel.top <- get.models(mod.sel, subset = delta < 4)

mod.ave <- model.avg(mod.sel.top)
summary(mod.ave)
```

# 3c 
```{r}
plot(mod.ave)
```